/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EAPKEXPANSIONFILE_AUTODEFS_H
#define S3EAPKEXPANSIONFILE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_APKEXPANSIONFILE_NAME "s3eApkExpansionFile"
#define S3E_EXT_APKEXPANSIONFILE_HASH 0xc70602e1

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eApkExpansionFile", 8)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EAPKEXPANSIONFILE_AUTODEFS_H */
