/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */

#include "s3eExt.h"
#include "IwDebug.h"
#include "s3eDevice.h"


#include "s3eApkExpansionFile.h"


#ifndef S3E_EXT_SKIP_LOADER_CALL_LOCK
// For MIPs (and WP8) platform we do not have asm code for stack switching
// implemented. So we make LoaderCallStart call manually to set GlobalLock
#if defined __mips || defined S3E_ANDROID_X86 || (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_PHONE_APP))
#define LOADER_CALL_LOCK
#endif
#endif

/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef  s3eResult(*s3eApkExpansionFileRegister_t)(s3eApkExpansionFileCallback cbid, s3eCallback fn, void* userData);
typedef  s3eResult(*s3eApkExpansionFileUnRegister_t)(s3eApkExpansionFileCallback cbid, s3eCallback fn);
typedef  s3eResult(*s3eApkExpansionFileInitialize_t)(const char* apiKey, const char* mainFileVersion, const char* patchFileVersion);
typedef const char*(*s3eApkExpansionFileGetPathToMainObb_t)();
typedef const char*(*s3eApkExpansionFileGetPathToPatchObb_t)();
typedef       bool(*s3eApkExpansionFileNeedDownloadMainObb_t)();
typedef       bool(*s3eApkExpansionFileNeedDownloadPatchObb_t)();
typedef       void(*s3eApkExpansionFileStartDownloading_t)();

/**
 * struct that gets filled in by s3eApkExpansionFileRegister
 */
typedef struct s3eApkExpansionFileFuncs
{
    s3eApkExpansionFileRegister_t m_s3eApkExpansionFileRegister;
    s3eApkExpansionFileUnRegister_t m_s3eApkExpansionFileUnRegister;
    s3eApkExpansionFileInitialize_t m_s3eApkExpansionFileInitialize;
    s3eApkExpansionFileGetPathToMainObb_t m_s3eApkExpansionFileGetPathToMainObb;
    s3eApkExpansionFileGetPathToPatchObb_t m_s3eApkExpansionFileGetPathToPatchObb;
    s3eApkExpansionFileNeedDownloadMainObb_t m_s3eApkExpansionFileNeedDownloadMainObb;
    s3eApkExpansionFileNeedDownloadPatchObb_t m_s3eApkExpansionFileNeedDownloadPatchObb;
    s3eApkExpansionFileStartDownloading_t m_s3eApkExpansionFileStartDownloading;
} s3eApkExpansionFileFuncs;

static s3eApkExpansionFileFuncs g_Ext;
static bool g_GotExt = false;
static bool g_TriedExt = false;
static bool g_TriedNoMsgExt = false;

static bool _extLoad()
{
    if (!g_GotExt && !g_TriedExt)
    {
        s3eResult res = s3eExtGetHash(0xc70602e1, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        else
            s3eDebugAssertShow(S3E_MESSAGE_CONTINUE_STOP_IGNORE,                 "error loading extension: s3eApkExpansionFile");

        g_TriedExt = true;
        g_TriedNoMsgExt = true;
    }

    return g_GotExt;
}

static bool _extLoadNoMsg()
{
    if (!g_GotExt && !g_TriedNoMsgExt)
    {
        s3eResult res = s3eExtGetHash(0xc70602e1, &g_Ext, sizeof(g_Ext));
        if (res == S3E_RESULT_SUCCESS)
            g_GotExt = true;
        g_TriedNoMsgExt = true;
        if (g_TriedExt)
            g_TriedExt = true;
    }

    return g_GotExt;
}

s3eBool s3eApkExpansionFileAvailable()
{
    _extLoadNoMsg();
    return g_GotExt ? S3E_TRUE : S3E_FALSE;
}

s3eResult s3eApkExpansionFileRegister(s3eApkExpansionFileCallback cbid, s3eCallback fn, void* userData)
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[0] func: s3eApkExpansionFileRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eApkExpansionFileRegister(cbid, fn, userData);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult s3eApkExpansionFileUnRegister(s3eApkExpansionFileCallback cbid, s3eCallback fn)
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[1] func: s3eApkExpansionFileUnRegister"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eApkExpansionFileUnRegister(cbid, fn);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

s3eResult s3eApkExpansionFileInitialize(const char* apiKey, const char* mainFileVersion, const char* patchFileVersion)
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[2] func: s3eApkExpansionFileInitialize"));

    if (!_extLoad())
        return S3E_RESULT_ERROR;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    s3eResult ret = g_Ext.m_s3eApkExpansionFileInitialize(apiKey, mainFileVersion, patchFileVersion);

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

const char* s3eApkExpansionFileGetPathToMainObb()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[3] func: s3eApkExpansionFileGetPathToMainObb"));

    if (!_extLoad())
        return NULL;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_s3eApkExpansionFileGetPathToMainObb();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

const char* s3eApkExpansionFileGetPathToPatchObb()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[4] func: s3eApkExpansionFileGetPathToPatchObb"));

    if (!_extLoad())
        return NULL;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    const char* ret = g_Ext.m_s3eApkExpansionFileGetPathToPatchObb();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool s3eApkExpansionFileNeedDownloadMainObb()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[5] func: s3eApkExpansionFileNeedDownloadMainObb"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_s3eApkExpansionFileNeedDownloadMainObb();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

bool s3eApkExpansionFileNeedDownloadPatchObb()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[6] func: s3eApkExpansionFileNeedDownloadPatchObb"));

    if (!_extLoad())
        return false;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    bool ret = g_Ext.m_s3eApkExpansionFileNeedDownloadPatchObb();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return ret;
}

void s3eApkExpansionFileStartDownloading()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile[7] func: s3eApkExpansionFileStartDownloading"));

    if (!_extLoad())
        return;

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallStart(S3E_TRUE, NULL);
#endif

    g_Ext.m_s3eApkExpansionFileStartDownloading();

#ifdef LOADER_CALL_LOCK
    s3eDeviceLoaderCallDone(S3E_TRUE, NULL);
#endif

    return;
}
