/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "s3eApkExpansionFile_autodefs.h"
#include "s3eEdk.h"
#include "s3eApkExpansionFile.h"
//Declarations of Init and Term functions
extern s3eResult s3eApkExpansionFileInit();
extern void s3eApkExpansionFileTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static s3eResult s3eApkExpansionFileInitialize_wrap(const char* apiKey, const char* mainFileVersion, const char* patchFileVersion)
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile func on main thread: s3eApkExpansionFileInitialize"));
    return (s3eResult)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eApkExpansionFileInitialize, 3, apiKey, mainFileVersion, patchFileVersion);
}

static const char* s3eApkExpansionFileGetPathToMainObb_wrap()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile func on main thread: s3eApkExpansionFileGetPathToMainObb"));
    return (const char*)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eApkExpansionFileGetPathToMainObb, 0);
}

static const char* s3eApkExpansionFileGetPathToPatchObb_wrap()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile func on main thread: s3eApkExpansionFileGetPathToPatchObb"));
    return (const char*)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eApkExpansionFileGetPathToPatchObb, 0);
}

static bool s3eApkExpansionFileNeedDownloadMainObb_wrap()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile func on main thread: s3eApkExpansionFileNeedDownloadMainObb"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eApkExpansionFileNeedDownloadMainObb, 0);
}

static bool s3eApkExpansionFileNeedDownloadPatchObb_wrap()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile func on main thread: s3eApkExpansionFileNeedDownloadPatchObb"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eApkExpansionFileNeedDownloadPatchObb, 0);
}

static void s3eApkExpansionFileStartDownloading_wrap()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile func on main thread: s3eApkExpansionFileStartDownloading"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eApkExpansionFileStartDownloading, 0);
}

static void s3eApkExpansionFileStopDownloading_wrap()
{
    IwTrace(APKEXPANSIONFILE_VERBOSE, ("calling s3eApkExpansionFile func on main thread: s3eApkExpansionFileStopDownloading"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)s3eApkExpansionFileStopDownloading, 0);
}

#define s3eApkExpansionFileInitialize s3eApkExpansionFileInitialize_wrap
#define s3eApkExpansionFileGetPathToMainObb s3eApkExpansionFileGetPathToMainObb_wrap
#define s3eApkExpansionFileGetPathToPatchObb s3eApkExpansionFileGetPathToPatchObb_wrap
#define s3eApkExpansionFileNeedDownloadMainObb s3eApkExpansionFileNeedDownloadMainObb_wrap
#define s3eApkExpansionFileNeedDownloadPatchObb s3eApkExpansionFileNeedDownloadPatchObb_wrap
#define s3eApkExpansionFileStartDownloading s3eApkExpansionFileStartDownloading_wrap
#define s3eApkExpansionFileStopDownloading s3eApkExpansionFileStopDownloading_wrap

#endif

s3eResult s3eApkExpansionFileRegister(s3eApkExpansionFileCallback cbid, s3eCallback fn, void* pData)
{
    return s3eEdkCallbacksRegister(S3E_EXT_APKEXPANSIONFILE_HASH, S3E_APKEXPANSIONFILE_CALLBACK_MAX, cbid, fn, pData, 0);
};

s3eResult s3eApkExpansionFileUnRegister(s3eApkExpansionFileCallback cbid, s3eCallback fn)
{
    return s3eEdkCallbacksUnRegister(S3E_EXT_APKEXPANSIONFILE_HASH, S3E_APKEXPANSIONFILE_CALLBACK_MAX, cbid, fn);
}

void s3eApkExpansionFileRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[9];
    funcPtrs[0] = (void*)s3eApkExpansionFileRegister;
    funcPtrs[1] = (void*)s3eApkExpansionFileUnRegister;
    funcPtrs[2] = (void*)s3eApkExpansionFileInitialize;
    funcPtrs[3] = (void*)s3eApkExpansionFileGetPathToMainObb;
    funcPtrs[4] = (void*)s3eApkExpansionFileGetPathToPatchObb;
    funcPtrs[5] = (void*)s3eApkExpansionFileNeedDownloadMainObb;
    funcPtrs[6] = (void*)s3eApkExpansionFileNeedDownloadPatchObb;
    funcPtrs[7] = (void*)s3eApkExpansionFileStartDownloading;
    funcPtrs[8] = (void*)s3eApkExpansionFileStopDownloading;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[9] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("s3eApkExpansionFile", funcPtrs, sizeof(funcPtrs), flags, s3eApkExpansionFileInit, s3eApkExpansionFileTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int s3eApkExpansionFileStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&s3eApkExpansionFileRegisterExt;
    return 0;
}

int g_s3eApkExpansionFileVal = s3eApkExpansionFileStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    s3eApkExpansionFileRegisterExt();
}
#endif

#endif
