/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ideaworks3d.marmalade.s3eApkExpansionFile;

public final class R {
    public static final class attr {
        /** 
    The size of the ad. It must be one of BANNER, FULL_BANNER, LEADERBOARD,
    MEDIUM_RECTANGLE, SMART_BANNER, WIDE_SKYSCRAPER, or
    &lt;width&gt;x&lt;height&gt;.
    
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adSize=0x7f010000;
        /** 
    A comma-separated list of the supported ad sizes. The sizes must be one of
    BANNER, FULL_BANNER, LEADERBOARD, MEDIUM_RECTANGLE, SMART_BANNER,
    WIDE_SKYSCRAPER, or &lt;width&gt;x&lt;height&gt;.
    
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adSizes=0x7f010001;
        /**  The ad unit ID. 
         <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int adUnitId=0x7f010002;
        /**  Appearance of the buy button. Must be one of "classic", "grayscale" and "monochrome" 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>grayscale</code></td><td>2</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>3</td><td></td></tr>
</table>
         */
        public static final int buyButtonAppearance=0x7f010018;
        /**  Height of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific height, e.g.
             "48dp", or special values "match_parent" and "wrap_content". 
         <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
         */
        public static final int buyButtonHeight=0x7f010015;
        /**  Text on the buy button. Must be one of "buy_with_google", "buy_now" and "book_now" 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buy_with_google</code></td><td>1</td><td></td></tr>
<tr><td><code>buy_now</code></td><td>2</td><td></td></tr>
<tr><td><code>book_now</code></td><td>3</td><td></td></tr>
</table>
         */
        public static final int buyButtonText=0x7f010017;
        /**  Width of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific width, e.g.
             "300dp", or special values "match_parent" and "wrap_content". 
         <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
         */
        public static final int buyButtonWidth=0x7f010016;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraBearing=0x7f010004;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLat=0x7f010005;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTargetLng=0x7f010006;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraTilt=0x7f010007;
        /** <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int cameraZoom=0x7f010008;
        /**  Google Wallet environment to use 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>production</code></td><td>1</td><td></td></tr>
<tr><td><code>sandbox</code></td><td>0</td><td></td></tr>
<tr><td><code>strict_sandbox</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int environment=0x7f010012;
        /**  Fragment mode 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buyButton</code></td><td>1</td><td></td></tr>
<tr><td><code>selectionDetails</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int fragmentMode=0x7f010014;
        /**  A style resource specifing attributes to customize the look and feel of WalletFragment 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int fragmentStyle=0x7f010013;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
         */
        public static final int mapType=0x7f010003;
        /**  Masked wallet details background 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int maskedWalletDetailsBackground=0x7f01001b;
        /**  "Change" button background in masked wallet details view 
         <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
         */
        public static final int maskedWalletDetailsButtonBackground=0x7f01001d;
        /**  TextAppearance for the "Change" button in masked wallet details view 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsButtonTextAppearance=0x7f01001c;
        /**  TextAppearance for headers describing masked wallet details 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsHeaderTextAppearance=0x7f01001a;
        /**  Type of the wallet logo image in masked wallet details view 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>2</td><td></td></tr>
</table>
         */
        public static final int maskedWalletDetailsLogoImageType=0x7f01001f;
        /**  Color of the Google Wallet logo text in masked wallet details view 
         <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int maskedWalletDetailsLogoTextColor=0x7f01001e;
        /**  TextAppearance for masked wallet details 
         <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int maskedWalletDetailsTextAppearance=0x7f010019;
        /**  Theme to be used for the Wallet selector 
         <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>holo_dark</code></td><td>0</td><td></td></tr>
<tr><td><code>holo_light</code></td><td>1</td><td></td></tr>
</table>
         */
        public static final int theme=0x7f010011;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiCompass=0x7f010009;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiRotateGestures=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiScrollGestures=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiTiltGestures=0x7f01000c;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomControls=0x7f01000d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int uiZoomGestures=0x7f01000e;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int useViewLifecycle=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int zOrderOnTop=0x7f010010;
    }
    public static final class color {
        public static final int common_action_bar_splitter=0x7f070009;
        /**  Sign-in Button Colors 
         */
        public static final int common_signin_btn_dark_text_default=0x7f070000;
        public static final int common_signin_btn_dark_text_disabled=0x7f070002;
        public static final int common_signin_btn_dark_text_focused=0x7f070003;
        public static final int common_signin_btn_dark_text_pressed=0x7f070001;
        public static final int common_signin_btn_default_background=0x7f070008;
        public static final int common_signin_btn_light_text_default=0x7f070004;
        public static final int common_signin_btn_light_text_disabled=0x7f070006;
        public static final int common_signin_btn_light_text_focused=0x7f070007;
        public static final int common_signin_btn_light_text_pressed=0x7f070005;
        public static final int common_signin_btn_text_dark=0x7f070017;
        public static final int common_signin_btn_text_light=0x7f070018;
        public static final int wallet_bright_foreground_disabled_holo_light=0x7f07000f;
        /** 
         Wallet colors to support consistent Wallet fragment holo dark UI in client application
         regardless of the theme and device type
    
         */
        public static final int wallet_bright_foreground_holo_dark=0x7f07000a;
        public static final int wallet_bright_foreground_holo_light=0x7f070010;
        public static final int wallet_dim_foreground_disabled_holo_dark=0x7f07000c;
        public static final int wallet_dim_foreground_holo_dark=0x7f07000b;
        public static final int wallet_dim_foreground_inverse_disabled_holo_dark=0x7f07000e;
        public static final int wallet_dim_foreground_inverse_holo_dark=0x7f07000d;
        public static final int wallet_highlighted_text_holo_dark=0x7f070014;
        public static final int wallet_highlighted_text_holo_light=0x7f070013;
        public static final int wallet_hint_foreground_holo_dark=0x7f070012;
        public static final int wallet_hint_foreground_holo_light=0x7f070011;
        public static final int wallet_holo_blue_light=0x7f070015;
        public static final int wallet_link_text_light=0x7f070016;
        public static final int wallet_primary_text_holo_light=0x7f070019;
        public static final int wallet_secondary_text_holo_dark=0x7f07001a;
    }
    public static final class dimen {
        public static final int page_loading_textview_textsize=0x7f0a0000;
    }
    public static final class drawable {
        public static final int android_icon_170x170_0=0x7f020000;
        public static final int common_signin_btn_icon_dark=0x7f020001;
        public static final int common_signin_btn_icon_disabled_dark=0x7f020002;
        public static final int common_signin_btn_icon_disabled_focus_dark=0x7f020003;
        public static final int common_signin_btn_icon_disabled_focus_light=0x7f020004;
        public static final int common_signin_btn_icon_disabled_light=0x7f020005;
        public static final int common_signin_btn_icon_focus_dark=0x7f020006;
        public static final int common_signin_btn_icon_focus_light=0x7f020007;
        public static final int common_signin_btn_icon_light=0x7f020008;
        public static final int common_signin_btn_icon_normal_dark=0x7f020009;
        public static final int common_signin_btn_icon_normal_light=0x7f02000a;
        public static final int common_signin_btn_icon_pressed_dark=0x7f02000b;
        public static final int common_signin_btn_icon_pressed_light=0x7f02000c;
        public static final int common_signin_btn_text_dark=0x7f02000d;
        public static final int common_signin_btn_text_disabled_dark=0x7f02000e;
        public static final int common_signin_btn_text_disabled_focus_dark=0x7f02000f;
        public static final int common_signin_btn_text_disabled_focus_light=0x7f020010;
        public static final int common_signin_btn_text_disabled_light=0x7f020011;
        public static final int common_signin_btn_text_focus_dark=0x7f020012;
        public static final int common_signin_btn_text_focus_light=0x7f020013;
        public static final int common_signin_btn_text_light=0x7f020014;
        public static final int common_signin_btn_text_normal_dark=0x7f020015;
        public static final int common_signin_btn_text_normal_light=0x7f020016;
        public static final int common_signin_btn_text_pressed_dark=0x7f020017;
        public static final int common_signin_btn_text_pressed_light=0x7f020018;
        public static final int dialog_full_holo_light=0x7f020019;
        public static final int gc_overlay_spinner=0x7f02001a;
        public static final int ic_plusone_medium_off_client=0x7f02001b;
        public static final int ic_plusone_small_off_client=0x7f02001c;
        public static final int ic_plusone_standard_off_client=0x7f02001d;
        public static final int ic_plusone_tall_off_client=0x7f02001e;
        public static final int icon=0x7f02001f;
        public static final int notify_panel_notification_icon_bg=0x7f020020;
        public static final int powered_by_google_dark=0x7f020021;
        public static final int powered_by_google_light=0x7f020022;
        public static final int progressbar_middle=0x7f020023;
        public static final int rounded_corners=0x7f020024;
        public static final int spinner_1=0x7f020025;
        public static final int spinner_10=0x7f020026;
        public static final int spinner_11=0x7f020027;
        public static final int spinner_12=0x7f020028;
        public static final int spinner_2=0x7f020029;
        public static final int spinner_3=0x7f02002a;
        public static final int spinner_4=0x7f02002b;
        public static final int spinner_5=0x7f02002c;
        public static final int spinner_6=0x7f02002d;
        public static final int spinner_7=0x7f02002e;
        public static final int spinner_8=0x7f02002f;
        public static final int spinner_9=0x7f020030;
        public static final int tw_widget_progressbar_effect_holo_light=0x7f020031;
        public static final int tw_widget_progressbar_holo_light=0x7f020032;
    }
    public static final class id {
        public static final int appIcon=0x7f080019;
        public static final int body=0x7f080016;
        public static final int book_now=0x7f080010;
        public static final int buyButton=0x7f08000a;
        public static final int buy_now=0x7f08000f;
        public static final int buy_with_google=0x7f08000e;
        public static final int classic=0x7f080011;
        public static final int description=0x7f08001f;
        public static final int grayscale=0x7f080012;
        public static final int holo_dark=0x7f080005;
        public static final int holo_light=0x7f080006;
        public static final int hybrid=0x7f080004;
        public static final int match_parent=0x7f08000c;
        public static final int message=0x7f080017;
        public static final int modal_alert_container=0x7f080014;
        public static final int modal_overlay_container=0x7f080015;
        public static final int monochrome=0x7f080013;
        public static final int none=0x7f080000;
        public static final int normal=0x7f080001;
        public static final int notificationLayout=0x7f080018;
        public static final int production=0x7f080007;
        public static final int progress_bar=0x7f08001e;
        public static final int progress_bar_frame=0x7f08001d;
        public static final int progress_text=0x7f08001a;
        public static final int sandbox=0x7f080008;
        public static final int satellite=0x7f080002;
        public static final int selectionDetails=0x7f08000b;
        public static final int strict_sandbox=0x7f080009;
        public static final int terrain=0x7f080003;
        public static final int time_remaining=0x7f08001c;
        public static final int title=0x7f08001b;
        public static final int wrap_content=0x7f08000d;
    }
    public static final class integer {
        public static final int google_play_services_version=0x7f090000;
    }
    public static final class layout {
        public static final int modal_alert_container=0x7f030000;
        public static final int modal_overlay_container=0x7f030001;
        public static final int progress_dialog=0x7f030002;
        public static final int status_bar_ongoing_event_progress_bar=0x7f030003;
    }
    public static final class raw {
        public static final int amazon_gc_prototype=0x7f040000;
    }
    public static final class string {
        public static final int IDS_SAPPS_BODY_WAITING_ING=0x7f05002b;
        public static final int IDS_SAPPS_HEADER_ITEM_PURCHASED=0x7f050030;
        public static final int IDS_SAPPS_POP_ALREADY_PURCHASED=0x7f05002d;
        public static final int IDS_SAPPS_POP_AN_ERROR_OCCURRED_WHILE_RESETTING_SAMSUNG_IN_APP_PURCHASE=0x7f050022;
        public static final int IDS_SAPPS_POP_AN_INVALID_VALUE_HAS_BEEN_PROVIDED_FOR_SAMSUNG_IN_APP_PURCHASE=0x7f050023;
        public static final int IDS_SAPPS_POP_AN_UNEXPECTED_ERROR_HAS_OCCURRED_SAMSUNG_ACCOUNT_AUTHENTICATION_HAS_BEEN_CANCELLED=0x7f050024;
        public static final int IDS_SAPPS_POP_A_NEW_VERSION_OF_SAMSUNG_IN_APP_PURCHASE_IS_AVAILABLE_UPDATE_Q=0x7f05002a;
        public static final int IDS_SAPPS_POP_NETWORK_UNAVAILABLE=0x7f05002f;
        public static final int IDS_SAPPS_POP_PAYMENT_CANCELLED=0x7f05002e;
        public static final int IDS_SAPPS_POP_PRODUCT_DOES_NOT_EXIST_IN_THIS_STORE=0x7f05002c;
        public static final int IDS_SAPPS_POP_SAMSUNG_IN_APP_PURCHASE=0x7f050027;
        public static final int IDS_SAPPS_POP_SAMSUNG_IN_APP_PURCHASE_NEEDS_TO_BE_UPDATED=0x7f050028;
        public static final int IDS_SAPPS_POP_TO_PURCHASE_ITEMS_YOU_NEED_TO_INSTALL_SAMSUNG_IN_APP_PURCHASE_INSTALL_Q=0x7f050029;
        public static final int IDS_SAPPS_POP_UNKNOWN_ERROR_OCCURRED=0x7f050026;
        public static final int IDS_SAPPS_POP_YOUR_PURCHASE_VIA_SAMSUNG_IN_APP_PURCHASE_IS_INVALID_A_FAKE_APPLICATION_HAS_BEEN_DETECTED_CHECK_THE_APP_MSG=0x7f050025;
        public static final int app_name=0x7f050000;
        public static final int auth_client_needs_enabling_title=0x7f050002;
        public static final int auth_client_needs_installation_title=0x7f050003;
        public static final int auth_client_needs_update_title=0x7f050004;
        public static final int auth_client_play_services_err_notification_msg=0x7f050005;
        public static final int auth_client_requested_by_msg=0x7f050006;
        public static final int auth_client_using_bad_version_title=0x7f050001;
        /**  Button in confirmation dialog to enable Google Play services.  Clicking it
        will direct user to application settings of Google Play services where they
        can enable it [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_enable_button=0x7f050012;
        /**  Message in confirmation dialog informing user they need to enable
        Google Play services in application settings [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_enable_text=0x7f050011;
        /**  Title of confirmation dialog informing user they need to enable
        Google Play services in application settings [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_enable_title=0x7f050010;
        /**   Requested by string saying which app requested the notification. [CHAR LIMIT=42] 
         */
        public static final int common_google_play_services_error_notification_requested_by_msg=0x7f05000b;
        /**  Button in confirmation dialog for installing Google Play services [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_install_button=0x7f05000f;
        /**  (For phones) Message in confirmation dialog informing user that
        they need to install Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_install_text_phone=0x7f05000d;
        /**  (For tablets) Message in confirmation dialog informing user that
        they need to install Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_install_text_tablet=0x7f05000e;
        /**  Title of confirmation dialog informing user that they need to install
        Google Play services (from Play Store) [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_install_title=0x7f05000c;
        /**  Message in confirmation dialog informing the user that they provided an invalid account. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_invalid_account_text=0x7f050018;
        /**  Title of confirmation dialog informing the user that they provided an invalid account. [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_invalid_account_title=0x7f050017;
        /**   Title for notification shown when GooglePlayServices needs to be enabled for an
        application to work. [CHAR LIMIT=70] 
         */
        public static final int common_google_play_services_needs_enabling_title=0x7f05000a;
        /**  Message in confirmation dialog informing the user that a network error occurred. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_network_error_text=0x7f050016;
        /**  Title of confirmation dialog informing the user that a network error occurred. [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_network_error_title=0x7f050015;
        /**   Title for notification shown when GooglePlayServices needs to be installed
        for an application to work. [CHAR LIMIT=70] 
         */
        public static final int common_google_play_services_notification_needs_installation_title=0x7f050008;
        /**   Title for notification shown when GooglePlayServices needs to be updated for an
        application to work. [CHAR LIMIT=70] 
         */
        public static final int common_google_play_services_notification_needs_update_title=0x7f050009;
        /**   Title for notification shown when GooglePlayServices is unavailable [CHAR LIMIT=42] 
         */
        public static final int common_google_play_services_notification_ticker=0x7f050007;
        /**  Message in confirmation dialog informing user there is an unknown issue in Google Play
        services [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unknown_issue=0x7f050019;
        /**  Message in confirmation dialog informing user that date on the device is not correct,
    causing certificate checks to fail. [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unsupported_date_text=0x7f05001c;
        /**  Message in confirmation dialog informing user that Google Play services is not supported on their device [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_unsupported_text=0x7f05001b;
        /**  Title of confirmation dialog informing user that Google Play services is not supported on their device [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_unsupported_title=0x7f05001a;
        /**  Button in confirmation dialog for updating Google Play services [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_update_button=0x7f05001d;
        /**  Message in confirmation dialog informing user that they need to update
        Google Play services (from Play Store) [CHAR LIMIT=NONE] 
         */
        public static final int common_google_play_services_update_text=0x7f050014;
        /**  Title of confirmation dialog informing user that they need to update
        Google Play services (from Play Store) [CHAR LIMIT=40] 
         */
        public static final int common_google_play_services_update_title=0x7f050013;
        /**  Sign-in button text [CHAR LIMIT=15] 
         */
        public static final int common_signin_button_text=0x7f05001e;
        /**  Long form sign-in button text [CHAR LIMIT=30] 
         */
        public static final int common_signin_button_text_long=0x7f05001f;
        public static final int dlg_msg_payment_success=0x7f050021;
        public static final int kilobytes_per_second=0x7f050045;
        /**  When a download completes, a notification is displayed, and this
        string is used to indicate that the download successfully completed.
        Note that such a download could have been initiated by a variety of
        applications, including (but not limited to) the browser, an email
        application, a content marketplace. 
         */
        public static final int notification_download_complete=0x7f050031;
        /**  When a download completes, a notification is displayed, and this
        string is used to indicate that the download failed.
        Note that such a download could have been initiated by a variety of
        applications, including (but not limited to) the browser, an email
        application, a content marketplace. 
         */
        public static final int notification_download_failed=0x7f050032;
        public static final int state_completed=0x7f050038;
        public static final int state_connecting=0x7f050036;
        public static final int state_downloading=0x7f050037;
        public static final int state_failed=0x7f050044;
        public static final int state_failed_cancelled=0x7f050043;
        public static final int state_failed_fetching_url=0x7f050041;
        public static final int state_failed_sdcard_full=0x7f050042;
        public static final int state_failed_unlicensed=0x7f050040;
        public static final int state_fetching_url=0x7f050035;
        public static final int state_idle=0x7f050034;
        public static final int state_paused_by_request=0x7f05003b;
        public static final int state_paused_network_setup_failure=0x7f05003a;
        public static final int state_paused_network_unavailable=0x7f050039;
        public static final int state_paused_roaming=0x7f05003e;
        public static final int state_paused_sdcard_unavailable=0x7f05003f;
        public static final int state_paused_wifi_disabled=0x7f05003d;
        public static final int state_paused_wifi_unavailable=0x7f05003c;
        public static final int state_unknown=0x7f050033;
        public static final int time_remaining=0x7f050046;
        public static final int time_remaining_notification=0x7f050047;
        /**  Text on a placeholder buy button when Google Play services is not
         available or up-to-date 
         */
        public static final int wallet_buy_button_place_holder=0x7f050020;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f060006;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f060007;
        public static final int ButtonBackground=0x7f06000e;
        public static final int GCAlert=0x7f060001;
        public static final int GCOverlay=0x7f060000;
        public static final int IapProgressBar=0x7f060008;
        public static final int NotificationText=0x7f06000b;
        public static final int NotificationTextSecondary=0x7f06000f;
        public static final int NotificationTextShadow=0x7f06000c;
        public static final int NotificationTitle=0x7f06000d;
        public static final int Theme_Empty=0x7f060009;
        public static final int Theme_Transparent=0x7f06000a;
        public static final int WalletFragmentDefaultButtonTextAppearance=0x7f060004;
        public static final int WalletFragmentDefaultDetailsHeaderTextAppearance=0x7f060003;
        public static final int WalletFragmentDefaultDetailsTextAppearance=0x7f060002;
        /** 
         Default style of the wallet fragment that will be used if not set explicitly
         when fragment is created
    
         */
        public static final int WalletFragmentDefaultStyle=0x7f060005;
    }
    public static final class styleable {
        /** Attributes that can be used with a AdsAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #AdsAttrs_adSize com.hullabu.ha1:adSize}</code></td><td>
    The size of the ad.</td></tr>
           <tr><td><code>{@link #AdsAttrs_adSizes com.hullabu.ha1:adSizes}</code></td><td>
    A comma-separated list of the supported ad sizes.</td></tr>
           <tr><td><code>{@link #AdsAttrs_adUnitId com.hullabu.ha1:adUnitId}</code></td><td> The ad unit ID.</td></tr>
           </table>
           @see #AdsAttrs_adSize
           @see #AdsAttrs_adSizes
           @see #AdsAttrs_adUnitId
         */
        public static final int[] AdsAttrs = {
            0x7f010000, 0x7f010001, 0x7f010002
        };
        /**
          <p>
          @attr description
          
    The size of the ad. It must be one of BANNER, FULL_BANNER, LEADERBOARD,
    MEDIUM_RECTANGLE, SMART_BANNER, WIDE_SKYSCRAPER, or
    &lt;width&gt;x&lt;height&gt;.
    


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:adSize
        */
        public static final int AdsAttrs_adSize = 0;
        /**
          <p>
          @attr description
          
    A comma-separated list of the supported ad sizes. The sizes must be one of
    BANNER, FULL_BANNER, LEADERBOARD, MEDIUM_RECTANGLE, SMART_BANNER,
    WIDE_SKYSCRAPER, or &lt;width&gt;x&lt;height&gt;.
    


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:adSizes
        */
        public static final int AdsAttrs_adSizes = 1;
        /**
          <p>
          @attr description
           The ad unit ID. 


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:adUnitId
        */
        public static final int AdsAttrs_adUnitId = 2;
        /** Attributes that can be used with a MapAttrs.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #MapAttrs_cameraBearing com.hullabu.ha1:cameraBearing}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLat com.hullabu.ha1:cameraTargetLat}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTargetLng com.hullabu.ha1:cameraTargetLng}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraTilt com.hullabu.ha1:cameraTilt}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_cameraZoom com.hullabu.ha1:cameraZoom}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_mapType com.hullabu.ha1:mapType}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiCompass com.hullabu.ha1:uiCompass}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiRotateGestures com.hullabu.ha1:uiRotateGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiScrollGestures com.hullabu.ha1:uiScrollGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiTiltGestures com.hullabu.ha1:uiTiltGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomControls com.hullabu.ha1:uiZoomControls}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_uiZoomGestures com.hullabu.ha1:uiZoomGestures}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_useViewLifecycle com.hullabu.ha1:useViewLifecycle}</code></td><td></td></tr>
           <tr><td><code>{@link #MapAttrs_zOrderOnTop com.hullabu.ha1:zOrderOnTop}</code></td><td></td></tr>
           </table>
           @see #MapAttrs_cameraBearing
           @see #MapAttrs_cameraTargetLat
           @see #MapAttrs_cameraTargetLng
           @see #MapAttrs_cameraTilt
           @see #MapAttrs_cameraZoom
           @see #MapAttrs_mapType
           @see #MapAttrs_uiCompass
           @see #MapAttrs_uiRotateGestures
           @see #MapAttrs_uiScrollGestures
           @see #MapAttrs_uiTiltGestures
           @see #MapAttrs_uiZoomControls
           @see #MapAttrs_uiZoomGestures
           @see #MapAttrs_useViewLifecycle
           @see #MapAttrs_zOrderOnTop
         */
        public static final int[] MapAttrs = {
            0x7f010003, 0x7f010004, 0x7f010005, 0x7f010006,
            0x7f010007, 0x7f010008, 0x7f010009, 0x7f01000a,
            0x7f01000b, 0x7f01000c, 0x7f01000d, 0x7f01000e,
            0x7f01000f, 0x7f010010
        };
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#cameraBearing}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:cameraBearing
        */
        public static final int MapAttrs_cameraBearing = 1;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#cameraTargetLat}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:cameraTargetLat
        */
        public static final int MapAttrs_cameraTargetLat = 2;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#cameraTargetLng}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:cameraTargetLng
        */
        public static final int MapAttrs_cameraTargetLng = 3;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#cameraTilt}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:cameraTilt
        */
        public static final int MapAttrs_cameraTilt = 4;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#cameraZoom}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a floating point value, such as "<code>1.2</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:cameraZoom
        */
        public static final int MapAttrs_cameraZoom = 5;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#mapType}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>none</code></td><td>0</td><td></td></tr>
<tr><td><code>normal</code></td><td>1</td><td></td></tr>
<tr><td><code>satellite</code></td><td>2</td><td></td></tr>
<tr><td><code>terrain</code></td><td>3</td><td></td></tr>
<tr><td><code>hybrid</code></td><td>4</td><td></td></tr>
</table>
          @attr name com.hullabu.ha1:mapType
        */
        public static final int MapAttrs_mapType = 0;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#uiCompass}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:uiCompass
        */
        public static final int MapAttrs_uiCompass = 6;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#uiRotateGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:uiRotateGestures
        */
        public static final int MapAttrs_uiRotateGestures = 7;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#uiScrollGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:uiScrollGestures
        */
        public static final int MapAttrs_uiScrollGestures = 8;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#uiTiltGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:uiTiltGestures
        */
        public static final int MapAttrs_uiTiltGestures = 9;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#uiZoomControls}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:uiZoomControls
        */
        public static final int MapAttrs_uiZoomControls = 10;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#uiZoomGestures}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:uiZoomGestures
        */
        public static final int MapAttrs_uiZoomGestures = 11;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#useViewLifecycle}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:useViewLifecycle
        */
        public static final int MapAttrs_useViewLifecycle = 12;
        /**
          <p>This symbol is the offset where the {@link com.hullabu.ha1.R.attr#zOrderOnTop}
          attribute's value can be found in the {@link #MapAttrs} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.hullabu.ha1:zOrderOnTop
        */
        public static final int MapAttrs_zOrderOnTop = 13;
        /**  Attributes for the WalletFragment &lt;fragment&gt; tag 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #WalletFragmentOptions_environment com.hullabu.ha1:environment}</code></td><td> Google Wallet environment to use </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_fragmentMode com.hullabu.ha1:fragmentMode}</code></td><td> Fragment mode </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_fragmentStyle com.hullabu.ha1:fragmentStyle}</code></td><td> A style resource specifing attributes to customize the look and feel of WalletFragment </td></tr>
           <tr><td><code>{@link #WalletFragmentOptions_theme com.hullabu.ha1:theme}</code></td><td> Theme to be used for the Wallet selector </td></tr>
           </table>
           @see #WalletFragmentOptions_environment
           @see #WalletFragmentOptions_fragmentMode
           @see #WalletFragmentOptions_fragmentStyle
           @see #WalletFragmentOptions_theme
         */
        public static final int[] WalletFragmentOptions = {
            0x7f010011, 0x7f010012, 0x7f010013, 0x7f010014
        };
        /**
          <p>
          @attr description
           Google Wallet environment to use 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>production</code></td><td>1</td><td></td></tr>
<tr><td><code>sandbox</code></td><td>0</td><td></td></tr>
<tr><td><code>strict_sandbox</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:environment
        */
        public static final int WalletFragmentOptions_environment = 1;
        /**
          <p>
          @attr description
           Fragment mode 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buyButton</code></td><td>1</td><td></td></tr>
<tr><td><code>selectionDetails</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:fragmentMode
        */
        public static final int WalletFragmentOptions_fragmentMode = 3;
        /**
          <p>
          @attr description
           A style resource specifing attributes to customize the look and feel of WalletFragment 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:fragmentStyle
        */
        public static final int WalletFragmentOptions_fragmentStyle = 2;
        /**
          <p>
          @attr description
           Theme to be used for the Wallet selector 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>holo_dark</code></td><td>0</td><td></td></tr>
<tr><td><code>holo_light</code></td><td>1</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:theme
        */
        public static final int WalletFragmentOptions_theme = 0;
        /**  Attributes that may be specified in a style resource to customize the look and feel of
         WalletFragment 
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonAppearance com.hullabu.ha1:buyButtonAppearance}</code></td><td> Appearance of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonHeight com.hullabu.ha1:buyButtonHeight}</code></td><td> Height of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonText com.hullabu.ha1:buyButtonText}</code></td><td> Text on the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_buyButtonWidth com.hullabu.ha1:buyButtonWidth}</code></td><td> Width of the buy button.</td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsBackground com.hullabu.ha1:maskedWalletDetailsBackground}</code></td><td> Masked wallet details background </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsButtonBackground com.hullabu.ha1:maskedWalletDetailsButtonBackground}</code></td><td> "Change" button background in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance com.hullabu.ha1:maskedWalletDetailsButtonTextAppearance}</code></td><td> TextAppearance for the "Change" button in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance com.hullabu.ha1:maskedWalletDetailsHeaderTextAppearance}</code></td><td> TextAppearance for headers describing masked wallet details </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsLogoImageType com.hullabu.ha1:maskedWalletDetailsLogoImageType}</code></td><td> Type of the wallet logo image in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsLogoTextColor com.hullabu.ha1:maskedWalletDetailsLogoTextColor}</code></td><td> Color of the Google Wallet logo text in masked wallet details view </td></tr>
           <tr><td><code>{@link #WalletFragmentStyle_maskedWalletDetailsTextAppearance com.hullabu.ha1:maskedWalletDetailsTextAppearance}</code></td><td> TextAppearance for masked wallet details </td></tr>
           </table>
           @see #WalletFragmentStyle_buyButtonAppearance
           @see #WalletFragmentStyle_buyButtonHeight
           @see #WalletFragmentStyle_buyButtonText
           @see #WalletFragmentStyle_buyButtonWidth
           @see #WalletFragmentStyle_maskedWalletDetailsBackground
           @see #WalletFragmentStyle_maskedWalletDetailsButtonBackground
           @see #WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance
           @see #WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance
           @see #WalletFragmentStyle_maskedWalletDetailsLogoImageType
           @see #WalletFragmentStyle_maskedWalletDetailsLogoTextColor
           @see #WalletFragmentStyle_maskedWalletDetailsTextAppearance
         */
        public static final int[] WalletFragmentStyle = {
            0x7f010015, 0x7f010016, 0x7f010017, 0x7f010018,
            0x7f010019, 0x7f01001a, 0x7f01001b, 0x7f01001c,
            0x7f01001d, 0x7f01001e, 0x7f01001f
        };
        /**
          <p>
          @attr description
           Appearance of the buy button. Must be one of "classic", "grayscale" and "monochrome" 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>grayscale</code></td><td>2</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>3</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:buyButtonAppearance
        */
        public static final int WalletFragmentStyle_buyButtonAppearance = 3;
        /**
          <p>
          @attr description
           Height of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific height, e.g.
             "48dp", or special values "match_parent" and "wrap_content". 


          <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:buyButtonHeight
        */
        public static final int WalletFragmentStyle_buyButtonHeight = 0;
        /**
          <p>
          @attr description
           Text on the buy button. Must be one of "buy_with_google", "buy_now" and "book_now" 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>buy_with_google</code></td><td>1</td><td></td></tr>
<tr><td><code>buy_now</code></td><td>2</td><td></td></tr>
<tr><td><code>book_now</code></td><td>3</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:buyButtonText
        */
        public static final int WalletFragmentStyle_buyButtonText = 2;
        /**
          <p>
          @attr description
           Width of the buy button. This includes an 8dp padding (4dp on each side) used for
             pressed and focused states of the button. The value can be a specific width, e.g.
             "300dp", or special values "match_parent" and "wrap_content". 


          <p>May be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
<p>May be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>match_parent</code></td><td>-1</td><td></td></tr>
<tr><td><code>wrap_content</code></td><td>-2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:buyButtonWidth
        */
        public static final int WalletFragmentStyle_buyButtonWidth = 1;
        /**
          <p>
          @attr description
           Masked wallet details background 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:maskedWalletDetailsBackground
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsBackground = 6;
        /**
          <p>
          @attr description
           "Change" button background in masked wallet details view 


          <p>May be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
<p>May be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:maskedWalletDetailsButtonBackground
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonBackground = 8;
        /**
          <p>
          @attr description
           TextAppearance for the "Change" button in masked wallet details view 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:maskedWalletDetailsButtonTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsButtonTextAppearance = 7;
        /**
          <p>
          @attr description
           TextAppearance for headers describing masked wallet details 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:maskedWalletDetailsHeaderTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsHeaderTextAppearance = 5;
        /**
          <p>
          @attr description
           Type of the wallet logo image in masked wallet details view 


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>classic</code></td><td>1</td><td></td></tr>
<tr><td><code>monochrome</code></td><td>2</td><td></td></tr>
</table>
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:maskedWalletDetailsLogoImageType
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoImageType = 10;
        /**
          <p>
          @attr description
           Color of the Google Wallet logo text in masked wallet details view 


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:maskedWalletDetailsLogoTextColor
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsLogoTextColor = 9;
        /**
          <p>
          @attr description
           TextAppearance for masked wallet details 


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          <p>This is a private symbol.
          @attr name com.hullabu.ha1:maskedWalletDetailsTextAppearance
        */
        public static final int WalletFragmentStyle_maskedWalletDetailsTextAppearance = 4;
    };
}
